#! /usr/bin/env bash
# Copyright 2026 Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

config="$(cat <<EOF

DPM_DOMAIN="${2}"
GOOGLE_PROJECT="${3}"

EOF
)"


d="install-scripts"
cat "${d}/template/header.sh" \
   <(echo "${config}") \
   "${d}/${1}.sh" \
   "${d}/template/body.sh"
