name: Update Tags
description: Update an OCI artifact tag in a registry using ORAS

inputs:
  version:
    description: Version to Update
    required: true
  component:
    description: Component to update
    required: true
  registry:
    description: Registry containing version to Update
    required: true
    default: "europe-docker.pkg.dev/da-images/public-unstable"
  tags:
    description: Tags to update as JSON array
    required: true
    default: '["devnet","testnet","mainnet"]'

runs:
  using: composite
  steps:
    - name: Update ${{ inputs.component }} latest tag
      run: |
        component_with_version=${{ inputs.registry }}/${{ inputs.component }}:${{ inputs.version }}
        echo '${{ inputs.tags }}' | jq -r '.[]' | while read -r tag; do
          echo "Tagging $component:$tag"
          oras tag --concurrency 1 "$component_with_version"  "$tag"
        done        

      shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail $0" "{0}"
