name: Update Tags
description: Update an OCI artifact tag in a registry using ORAS

inputs:
  version:
    description: Version to Update
    required: true
  component:
    description: Component to update
    required: true
  registry:
    description: Registry containing version to Update
    required: true
    default: "europe-docker.pkg.dev/da-images/public"
  tags:
    description: Tags to update as JSON array
    required: true
    default: '["devnet","testnet","mainnet"]'

runs:
  using: composite
  steps:
    - name: Update ${{ inputs.component }} tags
      run: |
        component_with_version=${{ inputs.registry }}/${{ inputs.component }}:${{ inputs.version }}
        
        # check SHA for this version 
        VERSION_DIGEST=$(oras resolve "${component_with_version}")
        
        for tag in $(echo '${{ inputs.tags }}' | jq -r '.[]'); do
          
          # check SHA for currently tag
          TAG_DIGEST=$(oras resolve "${{ inputs.registry }}/${{ inputs.component }}:$tag" 2>/dev/null || true)

          if [ "$VERSION_DIGEST" = "$TAG_DIGEST" ]; then
            echo "stable already points to version $tag"
          else
            echo "Tagging $component_with_version"
            oras tag --concurrency 1 "$component_with_version" "$tag"
          fi
        done
      shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail $0" "{0}"
