name: Get Splice/Canton Versions
description: Get Canton version via Splice version on the network
inputs:
  environment:
    description: "Canton environment: devnet, testnet, or mainnet"
    required: true
outputs:
  canton-version:
    description: Current Canton version
    value: ${{ steps.canton.outputs.canton-version }}
  splice-version:
    description: Current Splice version
    value: ${{ steps.canton.outputs.splice-version }}
  canton-major-minor:
    description: Current Splice version
    value: ${{ steps.canton.outputs.canton-major-minor }}

runs:
  using: composite
  steps:
    - name: Determine info URL
      id: environment
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        set -euo pipefail
        
        case "$ENVIRONMENT" in
          devnet)
            INFO_URL="https://docs.dev.global.canton.network.sync.global/info"
            ;;
          testnet)
            INFO_URL="https://docs.test.global.canton.network.sync.global/info"
            ;;
          mainnet)
            INFO_URL="https://docs.global.canton.network.sync.global/info"
            ;;
          *)
            echo "Invalid environment: $ENVIRONMENT"
            echo "Expected one of: devnet, testnet, mainnet"
            exit 1
            ;;
        esac
        echo "url=${INFO_URL}" >> "$GITHUB_OUTPUT"
      shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail {0}"

    - name: Determine current Splice version
      id: splice
      env:
        INFO_URL: ${{ steps.environment.outputs.url }}
      run: |
        set -euo pipefail

        SPLICE_VERSION="$(
          curl --fail --silent --show-error \
            "$INFO_URL" |
            jq -r '.synchronizer.current.version'
        )"

        if [[ -z "${SPLICE_VERSION}" || "${SPLICE_VERSION}" == "null" ]]; then
          echo "Failed to determine Splice version"
          exit 1
        fi

        echo "Splice version: ${SPLICE_VERSION}"
        echo "version=${SPLICE_VERSION}" >> "$GITHUB_OUTPUT"
      shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail {0}"

    - name: Get Canton Version from Splice Participant Image
      id: canton
      env:
        SPLICE_VERSION: ${{ steps.splice.outputs.version }}
      run: |
        set -euo pipefail
        
        IMAGE="ghcr.io/digital-asset/decentralized-canton-sync/docker/canton-participant:${SPLICE_VERSION}"
        
        echo "Using image: ${IMAGE}"
        
        CANTON_VERSION="$(
          docker run --rm \
            --entrypoint=/bin/sh \
            "${IMAGE}" \
            -c 'bin/canton --version' |
          grep '^Canton:' |
          awk '{print $2}'
        )"
        
        if [[ -z "${CANTON_VERSION}" ]]; then
          echo "Failed to determine Canton version"
          exit 1
        fi
        
        echo "Canton version: ${CANTON_VERSION}"
        
        MAJOR_MINOR="$(echo "${CANTON_VERSION}" | awk -F. '{print $1 "." $2}')"
        
        echo "canton-version=${CANTON_VERSION}" >> "$GITHUB_OUTPUT"
        echo "splice-version=${SPLICE_VERSION}" >> "$GITHUB_OUTPUT"
        echo "canton-major-minor=$MAJOR_MINOR" >> "$GITHUB_OUTPUT"


      shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail {0}"
