name: compliance

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - unlabeled

jobs:
  add-compliance-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Standard-Change label to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Standard-Change
