name: public-unstable-3-5

on:
  push:

  schedule:
    - cron: "0 10 * * 1-5"

defaults:
  run:
    shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail {0}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  READ_REGISTRY: 'europe-docker.pkg.dev/da-images/public-unstable'
  READ_GHCR_REGISTRY_DPM: 'ghcr.io/digital-asset/temp/temp'
  REGISTRY: 'europe-docker.pkg.dev/da-images/public-unstable'
  PROJECT: 'da-images'
  BUCKET: 'da-images-public-unstable'
  DOMAIN: 'get.digitalasset.com'

jobs:
  oci-bundle:
    runs-on: digital-asset-dpm-assembly
    outputs: 
      unstable_version: ${{ steps.versions2.outputs.unstable }}
      stable_version: ${{ steps.versions2.outputs.stable }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/nix
      - uses: ./.github/actions/gcloud-login
        with:
          key: ${{ secrets.DA_IMAGES }}
      - name: Versions
        id: versions2
        uses: ./.github/actions/versions
      - uses: ./.github/actions/release-unstable
        with:
          manifest: "latest/unstable/3.5.yaml"
          extra-tags: --extra-tags="${{ github.ref_name }}"
          
  docker:
    runs-on: digital-asset-dpm-assembly
    needs:
      - oci-bundle
    outputs:
      unstable-tag: ${{ steps.versions.outputs.unstable }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Login to GAR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: europe-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DA_IMAGES }}
      - uses: ./.github/actions/nix

      - name: Versions
        id: versions
        uses: ./.github/actions/versions

      - name: Docker Tags
        id: tags
        uses:  ./.github/actions/docker-tags
        with:
          name: "sdk"

      - name: Docker Build and Publish
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          push: true
          build-args: VERSION=${{ steps.versions.outputs.unstable }}
          tags: ${{ steps.tags.outputs.tags }}
          platforms: linux/amd64,linux/arm64

  docker-test:
    runs-on: digital-asset-dpm-assembly
    needs:
      - docker
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/nix
      - name: Login to GAR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: europe-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DA_IMAGES }}


      - name: Create temp writable directory
        run: |
          mkdir -p "$RUNNER_TEMP/my-temp-dir"
          echo "Temp dir: $RUNNER_TEMP/my-temp-dir"

      - name: Run Bats tests
        run: VERSION="${{ needs.docker.outputs.unstable-tag }}" bats ./test/dpm-docker.bats --report-formatter junit --output "${RUNNER_TEMP}/my-temp-dir"

      - name: Test Report
        uses: dorny/test-reporter@fe45e9537387dac839af0d33ba56eed8e24189e8 # v2.3.0
        with:
          name: docker tests
          path: ${{ runner.temp }}/my-temp-dir/*.xml
          reporter: java-junit
          fail-on-empty: false

  test-windows-archive-installation:
    runs-on: windows-latest
    timeout-minutes: 30
    needs:
      - oci-bundle
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Create temp dir
        run: |
          RUNNER_TEMP_DIR="${RUNNER_TEMP}/dpm-home"
          mkdir -p "${RUNNER_TEMP_DIR}"
          echo "DPM_HOME=${RUNNER_TEMP_DIR}" >> "${GITHUB_ENV}"
        shell: bash
      - name: Create new non-admin user
        run: |
          net user foo p@ssw0rd /add

          $pass = ConvertTo-SecureString "p@ssw0rd" -AsPlainText -Force
          $cred = [pscredential]::new("foo", $pass)

          ## This command should fail, validating that "foo" has no admin rights
          $p = Start-Process `
            -FilePath "cmd.exe" `
            -ArgumentList "/c net session" `
            -Credential $cred `
            -NoNewWindow `
            -Wait `
            -PassThru

          if ($p.ExitCode -eq 0) {
            throw "user appears to have admin rights"
          } else {
            Write-Host "non-admin confirmed"
          }
        shell: powershell
      - name: Download latest dpm windows archive
        run: |
          echo "Determining latest SDK tarball link..."

          ZIP_URL="$(curl -s https://get.digitalasset.com/unstable/install/latest-windows-archive.html | grep -oE 'https://[^ ]+\.zip')"
          ZIP_PATH="${RUNNER_TEMP}/dpm-windows-amd64.zip"

          if [ -z "${ZIP_URL}" ] ; then
            echo "Failed to determine latest SDK download link."
            exit 1
          fi
          echo "Latest SDK version tarball link is ${ZIP_URL}"

          curl -o "${ZIP_PATH}" "${ZIP_URL}"
        shell: bash
      - name: Run bootstrap as non-admin user
        shell: pwsh
        run: |
          $ZIP_PATH = "$env:RUNNER_TEMP/dpm-windows-amd64.zip"
          $EXTRACTED = Join-Path "$env:RUNNER_TEMP" "extracted"
          $exe = Join-Path $EXTRACTED "windows-amd64\bin\dpm.exe"

          Expand-Archive -Path $ZIP_PATH -DestinationPath $EXTRACTED

          $pass = ConvertTo-SecureString "p@ssw0rd" -AsPlainText -Force
          $cred = [pscredential]::new("foo", $pass)
          $argPath = Join-Path $EXTRACTED "windows-amd64"

          $cmd = "set `"DPM_LOG_LEVEL=debug`" && set `"DPM_HOME=$env:DPM_HOME`" && set `"TMP=$env:DPM_HOME`" && `"$exe`" bootstrap `"$argPath`""

          $p = Start-Process `
            -FilePath "cmd.exe" `
            -ArgumentList "/c $cmd" `
            -Credential $cred `
            -NoNewWindow `
            -Wait `
            -PassThru `
            
          if ($p.ExitCode -ne 0) { throw "exit code $($p.ExitCode)" }
      - name: verify installation
        shell: pwsh
        run: |
          $pass = ConvertTo-SecureString "p@ssw0rd" -AsPlainText -Force
          $cred = [pscredential]::new("foo", $pass)

          $exe = Join-Path $env:DPM_HOME "bin\dpm.cmd"

          # This command should fail unless temp dir is overriden to one the user has perms to 
          # (for writing the resolution file)
          $cmd = "set `"DPM_LOG_LEVEL=debug`" && set `"DPM_HOME=$env:DPM_HOME`" && set `"TMP=$env:DPM_HOME`" && `"$exe`" --help"

          $p = Start-Process `
            -FilePath "cmd.exe" `
            -ArgumentList "/c $cmd" `
            -Credential $cred `
            -NoNewWindow `
            -Wait `
            -PassThru `

          if ($p.ExitCode -ne 0) { throw "exit code $($p.ExitCode)" }

  test-release:
    uses: ./.github/workflows/test-release.yml
    needs:
      - oci-bundle
    with:
      registry: europe-docker.pkg.dev/da-images/public-unstable
      version-tag: ${{ needs.oci-bundle.outputs.stable_version }}

  update-tags:
    runs-on: digital-asset-dpm-assembly
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/nix
      - uses: ./.github/actions/gcloud-login
        with:
          key: ${{ secrets.DA_IMAGES }}
      - name: update tags for dpm
        uses: ./.github/actions/update-tags
        with:
          registry: europe-docker.pkg.dev/da-images/public
          component: components/dpm
          version: 1.0.21
          tag: latest

      - name: update tags for sdk devnet
        uses: ./.github/actions/update-tags
        with:
          registry: europe-docker.pkg.dev/da-images/public
          component: sdk-manifests/open-source
          version: 3.5.3
          tag: devnet

      - name: update tags for sdk testnet
        uses: ./.github/actions/update-tags
        with:
          registry: europe-docker.pkg.dev/da-images/public
          component: sdk-manifests/open-source
          version: 3.5.3
          tag: testnet

      - name: update tags for sdk mainnet
        uses: ./.github/actions/update-tags
        with:
          registry: europe-docker.pkg.dev/da-images/public
          component: sdk-manifests/open-source
          version: 3.5.2
          tag: mainnet

      - name: update tags for canton devnet
        uses: ./.github/actions/update-tags
        with:
          registry: europe-docker.pkg.dev/da-images/public
          component: components/canton-open-source
          version: 3.5.11
          tag: devnet

      - name: update tags for sdk testnet
        uses: ./.github/actions/update-tags
        with:
          registry: europe-docker.pkg.dev/da-images/public
          component: components/canton-open-source
          version: 3.5.10
          tag: testnet

      - name: update tags for sdk mainnet
        uses: ./.github/actions/update-tags
        with:
          registry: europe-docker.pkg.dev/da-images/public
          component: components/canton-open-source
          version: 3.5.9
          tag: mainnet
