name: public-unstable-weekly-pr

on:
  schedule:
    - cron: "0 8 * * 4" #every Thursday at 4:00 AM UTC
  workflow_dispatch:

defaults:
  run:
    shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail {0}"

jobs:
  create-pr:
    runs-on: digital-asset-dpm-assembly
    env:
      READ_REGISTRY: 'europe-docker.pkg.dev/da-images/public-all'
      READ_GHCR_REGISTRY_DPM: 'ghcr.io/digital-asset/temp/temp'
      REGISTRY: 'europe-docker.pkg.dev/da-images/public-unstable'
      PROJECT: 'da-images'
      BUCKET: 'da-images-public-unstable'
      DOMAIN: 'get.digitalasset.com'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTO_REBASE_PAT }}
      - uses: ./.github/actions/nix
      - uses: ./.github/actions/gcloud-login
        with:
          key: ${{ secrets.DA_IMAGES }}
      - name: 'download dpm'
        run: |
          echo "::group::Starting dpm installation"
          ./.github/get-dpm.sh "${REGISTRY}" main
          echo "::endgroup::"
      - name: 'open PR'
        run: |
          ./open-unstable-weekly-pr.sh
        env:
          GH_TOKEN: ${{ secrets.AUTO_REBASE_PAT }}
